// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnlcwcucfpzrmeycxkvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZubGN3Y3VjZnB6cm1leWN4a3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzYxMjksImV4cCI6MjA2NjM1MjEyOX0.CmoY9mWvt8g1F-7-NCLGnbkfA_jeZX2R7ADeLvPrTno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);